/*
 *
 *
脚本功能：百度网盘、在线画质清晰度、体验解锁下载速度
软件版本：13.10.5
下载地址：
脚本作者：GieGie666
更新时间：2025年
电报频道：https://t.me/GieGie777
问题反馈：
使用声明：此脚本仅供学习与交流，请在下载使用24小时内删除！请勿在中国大陆转载与贩卖！
*******************************
[rewrite_local]
# > 百度网盘、在线画质清晰度、体验解锁下载速度
^https?:\/\/pan\.baidu\.com.+(rest\/.+\/membership\/user|api\/user\/getinfo)\? url script-response-body https://raw.githubusercontent.com/ZZ1124/Rules/JS/Baiduyun.js
;^https?:\/\/.+(pcs\.baidu\.com|baidu\.com)\/rest\/2\.0\/pcs\/file\?.*\bfid= url script-request-header https://raw.githubusercontent.com/ZZ1124/Rules/JS/Baiduyun.js

[mitm] 
hostname = pan.baidu.com, *.pcs.baidu.com, *.baidu.com

*
*
*/
