#!name=Bilibili 1080P

#!desc=Bilibili解锁高清画质

#!homepage=https://whatshub.top

#!author=ddgksf2013

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/bili.png



^https?:\/\/app\.bilibili\.com\/x\/v2\/account\/myinfo\? url script-response-body https://raw.githubusercontent.com/ZZ1124/Rules/refs/heads/main/JS/Bilibili_json.js



hostname=app.bilibili.com
