[MITM]
hostname = sapi.beingfine.cn

[rewrite_local]

# [商店版]
#^https:\/\/sapi\.beingfine\.cn\/v3\/bb\/reward\/by-sign-in url script-request-header bubei.js

# [TestFlight]
^https:\/\/sapi\.beingfine\.cn\/v3\/bb\/reward\/by-sign-in url script-request-header https://raw.githubusercontent.com/chavyleung/scripts/master/bubei/bubei.js

[task_local]

# [商店版]
#1 0 * * * bubei.js

# [TestFlight]
1 0 * * * https://raw.githubusercontent.com/chavyleung/scripts/master/bubei/bubei.js
