

# ===== 开屏 / 弹窗 =====
^https:\/\/tiku\.fenbi\.com\/activity\/app\/launcher reject-dict
^https:\/\/keapi\.fenbi\.com\/app\/iphone\/\w+\/popup reject-dict
^https:\/\/market-api\.fenbi\.com\/iphone\/v1\/assistant\/info reject-dict
^https:\/\/market-api\.fenbi\.com\/iphone\/v1\/assistant\/entrance\/show reject-dict

# ===== 推荐 / 发现 =====
^https:\/\/hera-webapp\.fenbi\.com\/(iphone|ipad)\/recommend\/info reject-dict
^https:\/\/hera-webapp\.fenbi\.com\/(iphone|ipad)\/topic\/hotquery\/list reject-dict
^https:\/\/hera-webapp\.fenbi\.com\/(iphone|ipad)\/announcement\/hotquery\/list reject-dict
^https:\/\/hera-webapp\.fenbi\.com\/(iphone|ipad)\/explore\/consts reject-dict

# ===== Banner / 运营位 =====
^https:\/\/keapi\.fenbi\.com\/app\/(iphone|ipad)\/position_resource\/get_banners reject-dict
^https:\/\/keapi\.fenbi\.com\/app\/(iphone|ipad)\/position_resource\/get_home_banners reject-dict

# ===== 红点 =====
^https:\/\/keapi\.fenbi\.com\/app\/iphone\/\w+\/reddot reject-dict

# ===== App 配置 / 底部栏 =====
^https:\/\/ke\.fenbi\.com\/(iphone|ipad)\/v3\/apps\/config reject-dict

# ===== 课程 / 今日推荐 =====
^https:\/\/ke\.fenbi\.com\/(iphone|ipad)\/v3\/timetable\/today_with_public_episodes reject-dict

# ===== 会员入口 =====
^https:\/\/ke\.fenbi\.com\/(iphone|ipad)\/v3\/user_member\/entry reject-dict


hostname = keapi.fenbi.com, market-api.fenbi.com, ke.fenbi.com, hera-webapp.fenbi.com

