#2.4.5 需卸载重新安装优化
#author ZZ1124

^https:\/\/gateway\.kugou\.com\/youth\/api\/topic\/v1\/get_new_topic_list url reject-dict
#隐藏 搜索栏下 大家都在听 重写关闭开启，同步隐藏显示

^https:\/\/gateway\.kugou\.com\/youth\/v1\/channel\/tab_list url reject-dict
#隐藏 搜索栏下 推荐及其他分类榜单 重写关闭开启，同步隐藏显示

^https:\/\/gateway\.kugou\.com\/youth\/v2\/channel\/channel_all_list url reject-dict
#隐藏 发现 频道radio中的推荐频道 重写关闭开启，同步隐藏显示

^https:\/\/gateway\.kugou\.com\/youth\/api\/channel\/v2\/get_featured_channel url reject-dict
#隐藏 发现 推荐频道 

^https:\/\/gateway\.kugou\.com\/youth\/v1\/channel\/search_recommend_list url reject-dict
#隐藏 订阅 推荐频道

^https?://gateway\.kugou\.com/youth/api/operation/v1/get_play_background_img url script-response-body https://raw.githubusercontent.com/ZZ1124/Rules/main/JS/kugou_youth_bg_empty.js
#隐藏 发现 宝藏频道
^http://newsong\.kugou\.com/api/v1/recommend/index_v2 url script-response-body https://raw.githubusercontent.com/ZZ1124/Rules/main/JS/kugou_recommend_empty.js

^https:\/\/gateway\.kugou\.com\/youth\/api\/channel\/v5\/recommend_list url script-response-body https://raw.githubusercontent.com/ZZ1124/Rules/main/JS/kugou_youth_bg_empty.js
#隐藏 发现 宝藏频道下方片贴的下方所有片贴


########################################################
#^https:\/\/gateway\.kugou\.com\/youth\/api\/channel\/v1\/get_user_song url reject-dict
#^https:\/\/gateway\.kugou\.com\/youth\/v1\/channel_dress\/get_channel_dress_info url reject-dict
#^http:\/\/msg\.mobile\.kugou\.com\/v2\/pull\?_t url reject-dict
#^https:\/\/genesisapi\.kugou\.com\/v1\/content\/list url reject-dict
#^https:\/\/vipuser\.kugou\.com\/v1\/get_effect url reject-dict
#^http:\/\/config\.mobile\.kugou\.com\/v2\/appconfig url reject-dict
#^https:\/\/gateway\.kugou\.com\/youth\/api\/operation\/v1\/get_discovery_operation url reject-dict
#^http:\/\/d\.kugou\.com\/v2\/gen url reject-dict
#^https?://gateway\.kugou\.com/youth/v1/experiment/get_params url script-response-body https://raw.githubusercontent.com/ZZ1124/Rules/main/JS/kugou_youth_exp_noad.js
########################################################

hostname = gateway.kugou.com, newsong.kugou.com
