#2.4.5
^https:\/\/gateway\.kugou\.com\/youth\/api\/topic\/v1\/get_new_topic_list url reject-dict
#搜索栏下 大家都在听 隐藏

^https:\/\/gateway\.kugou\.com\/youth\/v1\/channel\/tab_list url reject-dict
#搜索栏下 推荐几其他分类榜单 隐藏

^https:\/\/gateway\.kugou\.com\/youth\/v2\/channel\/channel_all_list url reject-dict
#隐藏 发现 - 频道radio中的推荐频道

^https:\/\/gateway\.kugou\.com\/youth\/api\/channel\/v5\/recommend_list url reject-dict
#宝藏频道下方片贴的下方所有片贴不在更新

^https:\/\/gateway\.kugou\.com\/youth\/api\/channel\/v2\/get_featured_channel url reject-dict
#疑似推荐频道  

hostname = genesisapi.kugou.com
